### ISSUE TITLE
带木马训练中

### ISSUE THREAD

**Issue by 704227665** [nwpuhkp/DRL-Backdoor-Pong#2]
在带木马训练中的if self.time_to_poison or (self.poison_duration >= 0)中，clear_dispose(state)的state已经是一个（1,4,84,84）tensor了；此时的clear_dispose(state)为何要接受（1,4,84,84）的tensor，不应该是环境的下一个观测值吗，使用（1,4,84,84）的tensor导致clear_dispose(state)无法被正确使用
Traceback (most recent call last):
  File "C:\Users\70422\Downloads\DRL-Backdoor-Pong-master1\DRL-Backdoor-Pong-master\main.py", line 60, in <module>
    trainer.train()
  File "C:\Users\70422\Downloads\DRL-Backdoor-Pong-master1\DRL-Backdoor-Pong-master\dqn\Trainer.py", line 52, in train
    state = clear_dispose(state)
  File "C:\Users\70422\Downloads\DRL-Backdoor-Pong-master1\DRL-Backdoor-Pong-master\dqn\utils.py", line 42, in clear_dispose
    state_split[i] = gray_resize(state_split[i])
  File "C:\Users\70422\Downloads\DRL-Backdoor-Pong-master1\DRL-Backdoor-Pong-master\dqn\utils.py", line 12, in gray_resize
    gray_img = cv2.cvtColor(color_img, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.7.0) d:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0x73cf019b::Set<1,-1,-1>,struct cv::impl::A0x73cf019b::Set<0,2,5>,2>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

**Comment by k4pl3r** [comment]
已修改
